# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18m8wdIUbA9afRJJgQu442Jt17mvVeXZk
"""

a=float(input("enter the fno:"))
b=float(input("enter the sno:"))
c=float(input("enter the tno:"))
if a>b and a>c:
    print("fno is a larger number")
elif b>a and b>c:
    print("sno is a larger number")
elif c>a and c>b:
    print("tno is a larger number")
else:
    print("no number")